const availableTags = [
  "Itching",
  "Skin Rash",
  "Nodal Skin Eruptions",
  "Continuous Sneezing",
  "Shivering",
  "Chills",
  "Joint Pain",
  "Stomach Pain",
  "Acidity",
  "Ulcers On Tongue",
  "Muscle Wasting",
  "Vomiting",
  "Burning Micturition",
  "Spotting urination",
  "Fatigue",
  "Weight Gain",
  "Anxiety",
  "Cold Hands And Feets",
  "Mood Swings",
  "Weight Loss",
  "Restlessness",
  "Lethargy",
  "Patches In Throat",
  "Irregular Sugar Level",
  "Cough",
  "High Fever",
  "Sunken Eyes",
  "Breathlessness",
  "Sweating",
  "Dehydration",
  "Indigestion",
  "Headache",
  "Yellowish Skin",
  "Dark Urine",
  "Nausea",
  "Loss Of Appetite",
  "Pain Behind The Eyes",
  "Back Pain",
  "Constipation",
  "Abdominal Pain",
  "Diarrhoea",
  "Mild Fever",
  "Yellow Urine",
  "Yellowing Of Eyes",
  "Acute Liver Failure",
  "Fluid Overload",
  "Swelling Of Stomach",
  "Swelled Lymph Nodes",
  "Malaise",
  "Blurred And Distorted Vision",
  "Phlegm",
  "Throat Irritation",
  "Redness Of Eyes",
  "Sinus Pressure",
  "Runny Nose",
  "Congestion",
  "Chest Pain",
  "Weakness In Limbs",
  "Fast Heart Rate",
  "Pain During Bowel Movements",
  "Pain In Anal Region",
  "Bloody Stool",
  "Irritation In Anus",
  "Neck Pain",
  "Dizziness",
  "Cramps",
  "Bruising",
  "Obesity",
  "Swollen Legs",
  "Swollen Blood Vessels",
  "Puffy Face And Eyes",
  "Enlarged Thyroid",
  "Brittle Nails",
  "Swollen Extremeties",
  "Excessive Hunger",
  "Extra Marital Contacts",
  "Drying And Tingling Lips",
  "Slurred Speech",
  "Knee Pain",
  "Hip Joint Pain",
  "Muscle Weakness",
  "Stiff Neck",
  "Swelling Joints",
  "Movement Stiffness",
  "Spinning Movements",
  "Loss Of Balance",
  "Unsteadiness",
  "Weakness Of One Body Side",
  "Loss Of Smell",
  "Bladder Discomfort",
  "Foul Smell Of urine",
  "Continuous Feel Of Urine",
  "Passage Of Gases",
  "Internal Itching",
  "Toxic Look (typhos)",
  "Depression",
  "Irritability",
  "Muscle Pain",
  "Altered Sensorium",
  "Red Spots Over Body",
  "Belly Pain",
  "Abnormal Menstruation",
  "Dischromic Patches", //this is it
  "Watering From Eyes",
  "Increased Appetite",
  "Polyuria",
  "Family History",
  "Mucoid Sputum",
  "Rusty Sputum",
  "Lack Of Concentration",
  "Visual Disturbances",
  "Receiving Blood Transfusion",
  "Receiving Unsterile Injections",
  "Coma",
  "Stomach Bleeding",
  "Distention Of Abdomen",
  "History Of Alcohol Consumption",
  "Blood In Sputum",
  "Prominent Veins On Calf",
  "Palpitations",
  "Painful Walking",
  "Pus Filled Pimples",
  "Blackheads",
  "Scurring",
  "Skin Peeling",
  "Silver Like Dusting",
  "Small Dents In Nails",
];

const diseases = [
  {
    disease: "Fungal infection",
    specialty: "Dermatology",
  },
  {
    disease: "Allergy",
    specialty: "Allergy and Immunology",
  },
  {
    disease: "GERD",
    specialty: "Gastroenterology",
  },
  {
    disease: "Chronic cholestasis",
    specialty: "Gastroenterology",
  },
  {
    disease: "Drug Reaction",
    specialty: "Dermatology",
  },
  {
    disease: "Peptic ulcer diseae",
    specialty: "Gastroenterology",
  },
  {
    disease: "AIDS",
    specialty: "Infectious Disease",
  },
  {
    disease: "Diabetes ",
    specialty: "Endocrinology",
  },
  {
    disease: "Gastroenteritis",
    specialty: "Gastroenterology",
  },
  {
    disease: "Bronchial Asthma",
    specialty: "Pulmonology",
  },
  {
    disease: "Hypertension ",
    specialty: "Cardiology",
  },
  {
    disease: "Migraine",
    specialty: "Neurology",
  },
  {
    disease: "Cervical spondylosis",
    specialty: "Orthopedics",
  },
  {
    disease: "Paralysis (brain hemorrhage)",
    specialty: "Neurosurgery",
  },
  {
    disease: "Jaundice",
    specialty: "Gastroenterology",
  },
  {
    disease: "Malaria",
    specialty: "Infectious Disease",
  },
  {
    disease: "Chicken pox",
    specialty: "Pediatrics",
  },
  {
    disease: "Dengue",
    specialty: "Infectious Disease",
  },
  {
    disease: "Typhoid",
    specialty: "Infectious Disease",
  },
  {
    disease: "hepatitis A",
    specialty: "Gastroenterology",
  },
  {
    disease: "Hepatitis B",
    specialty: "Gastroenterology",
  },
  {
    disease: "Hepatitis C",
    specialty: "Gastroenterology",
  },
  {
    disease: "Hepatitis D",
    specialty: "Gastroenterology",
  },
  {
    disease: "Hepatitis E",
    specialty: "Gastroenterology",
  },
  {
    disease: "Alcoholic hepatitis",
    specialty: "Gastroenterology",
  },
  {
    disease: "Tuberculosis",
    specialty: "Infectious Disease",
  },
  {
    disease: "Common Cold",
    specialty: "Family Medicine",
  },
  {
    disease: "Pneumonia",
    specialty: "Pulmonology",
  },
  {
    disease: "Dimorphic hemmorhoids(piles)",
    specialty: "Gastroenterology",
  },
  {
    disease: "Heart attack",
    specialty: "Cardiology",
  },
  {
    disease: "Varicose veins",
    specialty: "Vascular surgery",
  },
  {
    disease: "Hypothyroidism",
    specialty: "Endocrinology",
  },
  {
    disease: "Hyperthyroidism",
    specialty: "Endocrinology",
  },
  {
    disease: "Hypoglycemia",
    specialty: "Endocrinology",
  },
  {
    disease: "Osteoarthristis",
    specialty: "Orthopedics",
  },
  {
    disease: "Arthritis",
    specialty: "Rheumatology",
  },
  {
    disease: "(vertigo) Paroymsal  Positional Vertigo",
    specialty: "Otolaryngology",
  },
  {
    disease: "Acne",
    specialty: "Dermatology",
  },
  {
    disease: "Urinary tract infection",
    specialty: "Urology",
  },
  {
    disease: "Psoriasis",
    specialty: "Dermatology",
  },
  {
    disease: "Impetigo",
    specialty: "Dermatology",
  },
];

let theDiseases = [];
for (let i = 0; i < diseases.length; i++) {
  theDiseases.push(diseases[i].disease);
}

const preDiseases = [
  "(vertigo) Paroymsal  Positional Vertigo",
  "AIDS",
  "Acne",
  "Alcoholic hepatitis",
  "Allergy",
  "Arthritis",
  "Bronchial Asthma",
  "Cervical spondylosis",
  "Chicken pox",
  "Chronic cholestasis",
  "Common Cold",
  "Dengue",
  "Diabetes ",
  "Dimorphic hemmorhoids(piles)",
  "Drug Reaction",
  "Fungal infection",
  "GERD",
  "Gastroenteritis",
  "Heart attack",
  "Hepatitis B",
  "Hepatitis C",
  "Hepatitis D",
  "Hepatitis E",
  "Hypertension ",
  "Hyperthyroidism",
  "Hypoglycemia",
  "Hypothyroidism",
  "Impetigo",
  "Jaundice",
  "Malaria",
  "Migraine",
  "Osteoarthristis",
  "Paralysis (brain hemorrhage)",
  "Peptic ulcer diseae",
  "Pneumonia",
  "Psoriasis",
  "Tuberculosis",
  "Typhoid",
  "Urinary tract infection",
  "Varicose veins",
  "hepatitis A",
];

const secondObj = [
  "Itching",
  "Skin Rash",
  "Nodal Skin Eruptions",
  "Continuous Sneezing",
  "Shivering",
  "Chills",
  "Joint Pain",
  "Stomach Pain",
  "Acidity",
  "Ulcers On Tongue",
  "Muscle Wasting",
  "Vomiting",
  "Burning Micturition",
  "Spotting urination",
  "Fatigue",
  "Weight Gain",
  "Anxiety",
  "Cold Hands And Feets",
  "Mood Swings",
  "Weight Loss",
  "Restlessness",
  "Lethargy",
  "Patches In Throat",
  "Irregular Sugar Level",
  "Cough",
  "High Fever",
  "Sunken Eyes",
  "Breathlessness",
  "Sweating",
  "Dehydration",
  "Indigestion",
  "Headache",
  "Yellowish Skin",
  "Dark Urine",
  "Nausea",
  "Loss Of Appetite",
  "Pain Behind The Eyes",
  "Back Pain",
  "Constipation",
  "Abdominal Pain",
  "Diarrhoea",
  "Mild Fever",
  "Yellow Urine",
  "Yellowing Of Eyes",
  "Acute Liver Failure",
  "Fluid Overload",
  "Swelling Of Stomach",
  "Swelled Lymph Nodes",
  "Malaise",
  "Blurred And Distorted Vision",
  "Phlegm",
  "Throat Irritation",
  "Redness Of Eyes",
  "Sinus Pressure",
  "Runny Nose",
  "Congestion",
  "Chest Pain",
  "Weakness In Limbs",
  "Fast Heart Rate",
  "Pain During Bowel Movements",
  "Pain In Anal Region",
  "Bloody Stool",
  "Irritation In Anus",
  "Neck Pain",
  "Dizziness",
  "Cramps",
  "Bruising",
  "Obesity",
  "Swollen Legs",
  "Swollen Blood Vessels",
  "Puffy Face And Eyes",
  "Enlarged Thyroid",
  "Brittle Nails",
  "Swollen Extremeties",
  "Excessive Hunger",
  "Extra Marital Contacts",
  "Drying And Tingling Lips",
  "Slurred Speech",
  "Knee Pain",
  "Hip Joint Pain",
  "Muscle Weakness",
  "Stiff Neck",
  "Swelling Joints",
  "Movement Stiffness",
  "Spinning Movements",
  "Loss Of Balance",
  "Unsteadiness",
  "Weakness Of One Body Side",
  "Loss Of Smell",
  "Bladder Discomfort",
  "Foul Smell Of urine",
  "Continuous Feel Of Urine",
  "Passage Of Gases",
  "Internal Itching",
  "Toxic Look (typhos)",
  "Depression",
  "Irritability",
  "Muscle Pain",
  "Altered Sensorium",
  "Red Spots Over Body",
  "Belly Pain",
  "Abnormal Menstruation",
  "Dischromic Patches",
  "Watering From Eyes",
  "Increased Appetite",
  "Polyuria",
  "Family History",
  "Mucoid Sputum",
  "Rusty Sputum",
  "Lack Of Concentration",
  "Visual Disturbances",
  "Receiving Blood Transfusion",
  "Receiving Unsterile Injections",
  "Coma",
  "Stomach Bleeding",
  "Distention Of Abdomen",
  "History Of Alcohol Consumption",
  "Fluid Overload.1",
  "Blood In Sputum",
  "Prominent Veins On Calf",
  "Palpitations",
  "Painful Walking",
  "Pus Filled Pimples",
  "Blackheads",
  "Scurring",
  "Skin Peeling",
  "Silver Like Dusting",
  "Small Dents In Nails",
  "Inflammatory Nails",
  "Blister",
  "Red Sore Around Nose",
  "Yellow Crust Ooze",
];

function compareArrays(array1, array2) {
  let missingElements = [];
  //   for (let i = 0; i < array1.length; i++) {
  //     if (!array2.includes(array1[i])) {
  //       missingElements.push(array1[i]);
  //     }
  //   }
  for (let i = 0; i < array2.length; i++) {
    if (!array1.includes(array2[i])) {
      missingElements.push(array2[i]);
    }
  }
  return missingElements;
}

console.log(compareArrays(theDiseases, preDiseases));
